config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :users, except: [:new, :create]
  root 'homes#home'
  get 'about', to: 'homes#about'
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  has_secure_password :recovery_password, validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new', status: :unprocessable_entity
    end

  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit', status: :unprocessable_entity
    end

  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your detail"
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:alert] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :edit, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "#{@user.username} Singed up"
      redirect_to articles_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to user_path(@user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/articles/_article.html.erb
<div class="card mb-3">
  <div class="card-header font-italic ml-2">
    <% if article.user %>
      By <%= link_to article.user.username, user_path(article.user) %>
    <% end %>
  </div>
  <br>
  <p class="card-text">
    <strong>Title:</strong> <%= article.title %>
  </p>

  <p class="card-text">
    <strong>Description:</strong> <%= article.description %>
  </p>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true, html: { class: 'mt-4' }) do |f| %>

  <div class="col-sm-2">
    <%= f.label :title, class: 'form-label' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="col-sm-2">
    <%= f.label :description, class: 'form-label' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="mb-3 mt-3">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= render 'shared/error', obj: @article %>
<%= render 'form'%>

<%= link_to 'Cancel and return to articles listing', articles_path, class: 'btn btn-secondary' %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<div class="flickr_pagination ">
  <%= will_paginate @articles, :container => false, class: "mb-5" %>
</div>


<div id="articles" class="mt-4">
  <% @articles.each do |article| %>
    <%= render 'article', article: article %>
    <p>
      <%= link_to "Show this article", article, class: 'btn btn-primary me-2' %>
      <% if logged_in? && (article.user == current_user || current_user.admin?) %>
        <%= link_to "Edit Article", edit_article_path(article), class: 'btn btn-secondary' %>

      <%= link_to 'Delete', article_path(article),
                  class: 'btn btn-danger',
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
      <% end %>
        </p>

  <% end %>
</div>
<% if logged_in?%>
  <p>
    <%= link_to "Create new article", new_article_path, class: 'btn btn-success mt-3' %>
  </p>
<% end %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false, class: "mb-10" %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>
<%= render 'shared/error', obj: @article %>
<%= render 'form' %>


<%= link_to 'Cancel and return to articles listing', articles_path, class: 'btn btn-secondary' %>

app/views/articles/show.html.erb
<div class="container mt-4">
  <h1><%= @article.title.capitalize %>'s article Details</h1>

  <div class="card mt-4">
    <div class="card-body">
      <p class="card-text"><strong>Title:</strong> <%= @article.title %></p>
      <p class="card-text"><strong>Description:</strong> <%= @article.description %></p>
      <p class="card-text"><strong>Username:</strong> <%= @article.user.username if @article.user %></p>
    </div>
  </div>

  <div class="mt-4">
    <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
      <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-primary me-2' %>
      <%= link_to 'Delete', article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger me-2' %>
    <% end %>
    <%= link_to 'Return to Articles Listing', articles_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/homes/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>About Page</title>
  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container mt-5">
  <h1>This is About Page</h1>

  <div class="alert alert-info">
    <p>Welcome to our about page. Learn more about our mission and vision.</p>
  </div>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Our Mission</h5>
      <p class="card-text">To provide valuable information and resources to our community.</p>
    </div>
  </div>

  <div class="card mt-3">
    <div class="card-body">
      <h5 class="card-title">Our Vision</h5>
      <p class="card-text">To create a platform that inspires and educates people around the world.</p>
    </div>
  </div>

  <p class="mt-4">
    <%= link_to 'Articles listing', articles_path, class: 'btn btn-primary mr-2' %>
    <%= link_to 'Home page', root_path, class: 'btn btn-secondary' %>
  </p>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>

app/views/homes/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Home Page</title>
</head>
<body>

<div class="container mt-5">
  <h1>This is the Home page</h1>

  <div class="alert alert-info">
    <p>Welcome to our platform! Explore the latest articles and engage with our community.</p>
  </div>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Featured Articles</h5>
      <p class="card-text">Discover our handpicked selection of articles that cover a variety of topics.</p>
    </div>
  </div>

  <div class="card mt-3">
    <div class="card-body">
      <h5 class="card-title">Community Forum</h5>
      <p class="card-text">Join discussions, ask questions, and connect with like-minded individuals in our forum.</p>
    </div>
  </div>

  <p class="mt-4">
    <%= link_to 'Articles listing page', articles_path, class: 'btn btn-primary mr-2' %>
    <%= link_to 'About page', about_path, class: 'btn btn-secondary mr-2' %>
    <%= link_to "Sign up", signup_path, class: 'btn btn-success' %>
  </p>
</div>


</body>
</html>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'layouts/messages' %>
    <div style="margin:10px;">
      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <h2>The following errors prevented the <%= obj.class.name.downcase %> from being saved</h2>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href='<%= root_path %>'>Alpha Blog </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href='<%= users_path %>'>Bloggers </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= articles_path %>">Articles </a>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to current_user.username, user_path(current_user), class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log out', logout_path, class: "nav-link active", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </li>
          <% if current_user.admin? %>
            <li class="nav-item">
              <a class="nav-link active" href="#">Admin </a>
            </li>
          <% end %>
        <% else %>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= login_path %>">Log in </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="<%= signup_path %>">Sign up </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true, html: { class: 'mt-4' }) do |f| %>

  <div class="mb-3 ">
    <div class="col-sm-2">
      <%= f.label :username, class: 'form-label' %><br/>
      <%= f.text_field :username, class: 'form-control mb-2' %>
    </div>

    <div class="col-sm-2">
      <%= f.label :email, class: 'form-label' %><br/>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
  </div>

  <div class="col-sm-2">
    <%= f.label :password, class: 'form-label' %><br/>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="mb-3 mt-3">
    <%= f.submit(@user.new_record? ? "Sign up" : "Update Acc", class: 'btn btn-primary') %>
  </div>

<% end %>

app/views/users/_user.html.erb
<h1><%= user.username %>'s Details</h1>

<p class="card-text">
  <strong>Username:</strong> <%= link_to user.username, user %></p>
<p class="card-text"><strong>Email:</strong> <%= user.email %></p>
<p class="card-text"><strong>Articles:</strong>
  <% user.articles.each_with_index do |article, index| %>
    <%= link_to article.title, article %>
    <% unless index == user.articles.size - 1 %>
      &ndash;
    <% end %>
  <% end %>
</p>
<p class="card-text">
<div class="mt-2">
  <%= link_to "Detail of User", user,
              class: 'btn btn-primary me-2' %>
  <% if logged_in? %>
    <% if user == current_user %>
      <%= link_to "Edit User's Data", edit_user_path(user),
                  class: 'btn btn-secondary' %>
    <% end %>
    <% if current_user.admin? %>
      <%= link_to 'Delete', user_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                  class: 'btn btn-danger' %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h3>Edit Profile for Alpha Blog</h3>
<%= render 'shared/error', obj: @user %>
<%= render 'form' %>


<%= link_to 'Cancel and return to articles listing', articles_path, class: 'btn btn-secondary' %>

app/views/users/index.html.erb
<div class="container mt-4">
  <h1 class="text-center">Alpha Bloggers</h1>

  <div class="flickr_pagination ">
    <%= will_paginate @users, :container => false %>
  </div>


  <% @users.each do |user| %>
    <div class="card mt-4">
      <div class="card-body">
        <%= render 'user', user: user %>
      </div>
      <div class="card-footer text-muted">
        <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
      </div>
    </div>
  <% end %>
  <% if !logged_in? %>
    <div class="mt-4">
      <%= link_to "Sign up", signup_path, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-2">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1>Sign up for Alpha Blog</h1>
<%= render 'shared/error', obj: @user %>
<%= render 'form' %>


<%= link_to 'Cancel and return to articles listing', articles_path, class: 'btn btn-secondary' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>
<% if logged_in? and @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user),
                class: "btn btn-outline-info" %>
    <%= link_to "Delete Profile", user_path(@user),
                data: { turbo_method: :delete, turbo_confirm: "Are you Sure" },
                class: "btn btn-outline-danger" %>
  </div>
<% end %>
<h3 class="text-center mt-4">Articles</h3>
<% @articles.each do |article| %>
  <%= render 'articles/article', article: article %>
<% end %>